"use client";

import { useState, type ReactNode } from "react";
import Image from "next/image";
import { useSearchParams } from "next/navigation";
import { ArrowLeft, ArrowUpLeft, ArrowRight, Check, Code2, Cpu, Play, RotateCcw, Sparkles, Zap } from "lucide-react";
import { conceptDirections, type ConceptVariant } from "./directions";
import s from "./worlds.module.css";

const samples = [
  { title: "מה באמת עושה XOR?", topic: "לוגיקה ספרתית", prompt: "נתונים שני קלטים בינאריים A ו־B. תכננו מוצא ששווה ל־1 רק כאשר הקלטים שונים. כתבו את טבלת האמת והסבירו איך אפשר לממש את הפעולה באמצעות AND, OR ו־NOT.", hint: "יש שני מקרים שבהם המוצא צריך להיות 1: A=1 ו־B=0, או A=0 ו־B=1.", answer: "Y = (A AND NOT B) OR (NOT A AND B). בטבלת האמת, 00 ו־11 נותנים 0; הצירופים 01 ו־10 נותנים 1." },
  { title: "למצוא את המספר החסר", topic: "תכנות ואלגוריתמים", prompt: "מערך מכיל את כל המספרים מ־0 עד n, פרט למספר אחד, בלי כפילויות. מצאו את המספר החסר בזמן ליניארי ובזיכרון נוסף קבוע. הסבירו את ההנחות שלכם.", hint: "מספר שעובר XOR עם עצמו נותן 0. מה יקרה אם נעבור על כל המספרים בטווח וגם על כל איברי המערך?", answer: "מבצעים XOR של כל המספרים מ־0 עד n ושל כל איברי המערך. כל מספר שמופיע פעמיים מתאפס, ולכן נשאר רק המספר החסר. זמן O(n), זיכרון נוסף O(1)." },
  { title: "מה הזווית בשש וחצי?", topic: "חשיבה לוגית", prompt: "מהי הזווית הקטנה בין המחוגים בשעה 6:30? הסבירו איך הבאתם בחשבון את תנועת מחוג השעות.", hint: "מחוג השעות ממשיך לנוע בזמן שמחוג הדקות מתקדם. בחצי שעה הוא עובר חצי מהדרך בין שתי ספרות.", answer: "מחוג הדקות נמצא ב־180°. מחוג השעות נמצא ב־195°: שש פעמים 30° ועוד 15° עבור חצי שעה. הזווית הקטנה היא 15°." },
];
type Start = (index?: number) => void;

function Action({ children = "מתחילים לתרגל", start, index = 0 }: { children?: ReactNode; start: Start; index?: number }) {
  return <button className={s.action} onClick={() => start(index)}>{children}<ArrowUpLeft size={21} strokeWidth={1.8} /></button>;
}
function Header({ start, marker }: { start: Start; marker?: ReactNode }) {
  return <header className={s.header}><a href="/design-lab" className={s.brand} aria-label="JobRun — גלריית עיצובים" dir="ltr">jobrun<span>.</span>{marker}</a><nav aria-label="ניווט בהדמיה"><a href="#explore">מה מתרגלים</a><button onClick={() => start(1)}>שאלה לדוגמה</button></nav><button className={s.navAction} onClick={() => start()}>בואו נתחיל <ArrowLeft size={16} /></button></header>;
}
function TopicFooter({ start, lead = "ידע מקבל צורה כשמתרגלים אותו." }: { start: Start; lead?: string }) {
  return <section id="explore" className={s.explore}><h2>{lead}</h2><div className={s.topicRows}>{samples.map((q, i) => <button onClick={() => start(i)} key={q.title}><span>{q.topic}</span><strong>{q.title}</strong><ArrowUpLeft size={23} /></button>)}</div><p>שאלות, רמזים ומקום להסביר את הדרך שלכם. בקצב שמתאים לכם.</p></section>;
}
function Chip({ a, b }: { a: number; b: number }) {
  return <div className={s.chipScene} aria-hidden="true"><div className={s.orbit} /><div className={s.orbitTwo} /><div className={s.die}><Image src="/design-worlds/ion-chip.png" alt="" fill sizes="(max-width:700px) 300px, 400px" priority /><strong>{a ^ b}</strong></div><span className={s.orbitLabel}>A ⊕ B</span></div>;
}
function Ion({ start }: { start: Start }) {
  const [a, setA] = useState(1), [b, setB] = useState(0);
  return <><Header start={start} marker={<i />} /><section className={s.ionHero}><div className={s.ionCopy}><h1>הרעיון הבא<br />מתחיל <em>אצלך.</em></h1><p>הכנה לראיונות חומרה ותוכנה.<br />לפתור, לפרק, להבין — ולהגיע עם ביטחון.</p><Action start={start} /><div className={s.ionTracks}><span>Digital design</span><span>Code</span><span>Logic</span></div></div><div className={s.ionArt}><Chip a={a} b={b} /><div className={s.ionInputs} dir="ltr"><button onClick={() => setA(1-a)} aria-label={`קלט A: ${a}`}>A <b>{a}</b></button><button onClick={() => setB(1-b)} aria-label={`קלט B: ${b}`}>B <b>{b}</b></button><span>Y = <output aria-live="polite">{a ^ b}</output></span></div><p>שני קלטים. לחצו, ושנו את התוצאה.</p></div></section><TopicFooter start={start} /></>;
}
function Coral({ start }: { start: Start }) {
  const [bits, setBits] = useState([1,0]);
  return <><Header start={start} /><section className={s.coralHero}><div className={s.coralTitle}><h1>יש לך<br /><span>את זה.</span></h1><div className={s.coralIntro}><p>עכשיו נלמד להראות את זה.<br />מרחב לתרגול ראיונות, ניסוי וטעייה,<br />והרגע שבו הדברים מתחברים.</p><Action start={start}>בואו ננסה שאלה</Action></div></div><div className={s.switchPoster}><div className={s.switchTop}><span dir="ltr">THINK. SWITCH. REPEAT.</span><Zap size={34} fill="currentColor" /></div><div className={s.bigSwitches} dir="ltr"><Image src="/design-worlds/coral-buttons.png" alt="" fill sizes="(max-width:700px) 300px, 400px" priority />{bits.map((bit,i)=><button key={i} aria-label={`מתג ${i===0?'A':'B'}: ${bit}`} aria-pressed={!!bit} onClick={()=>setBits(old=>old.map((v,n)=>n===i?1-v:v))}><span>{i===0?'A':'B'}</span><b>{bit}</b></button>)}</div><div className={s.switchAnswer}><span>שונים? המוצא נדלק.</span><output aria-live="polite">{bits[0]^bits[1]}</output></div></div></section><div className={s.coralStrip}><span>סקרנות</span><ArrowLeft /><span>ניסוי</span><ArrowLeft /><span>הבנה</span></div><TopicFooter start={start} lead="פחות לשנן. יותר להבין." /></>;
}
function Blueprint({ start }: { start: Start }) {
  const [gate,setGate]=useState("XOR");
  return <><Header start={start} /><section className={s.blueHero}><div className={s.blueTitle}><h1>מתכננים<br />את הצעד<br /><em>הבא.</em></h1><p>מהידע של התואר לשיחה בראיון.<br />תרגול ממוקד, מהיסוד עד לפתרון.</p><Action start={start} /></div><div className={s.blueSheet}><div className={s.sheetRule}><code>LOGIC / EXPERIMENT</code><span>שנו את השער</span></div><svg viewBox="0 0 560 355" role="img" aria-label={`שער ${gate} עם קלטים 1 ו־1, מוצא ${gate==='XOR'?0:1}`}><defs><marker id="arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="currentColor" /></marker></defs><path className={s.blueGuide} d="M45 62H510M45 299H510M103 25V325M465 25V325" /><path className={s.blueWire} d="M55 133H205M55 219H205M394 176H500" /><path className={s.blueGate} d="M205 87H394V265H205Z" /><text x="263" y="187">{gate}</text><text x="62" y="112">A = 1</text><text x="62" y="258">B = 1</text><circle cx="486" cy="176" r="29" /><text className={s.blueResult} x="478" y="185">{gate==='XOR'?0:1}</text><path className={s.blueMeasure} d="M205 312H372M205 302V322M372 302V322" /><text x="253" y="346">Y = A {gate==='XOR'?'⊕':gate==='AND'?'·':'+'} B</text></svg><div className={s.gatePicker} dir="ltr">{['AND','OR','XOR'].map(g=><button key={g} aria-pressed={gate===g} onClick={()=>setGate(g)}>{g}</button>)}</div><p>אותם קלטים. פעולה אחרת. מסקנה חדשה.</p></div></section><div className={s.blueLegend}><span>לוגיקה ספרתית</span><span>תכנון מעגלים</span><span>אלגוריתמים</span><span>חשיבה לוגית</span></div><TopicFooter start={start} /></>;
}
function Chrome({ start }: { start: Start }) {
  const [bits,setBits]=useState([1,0,1,0]);
  const value=bits.reduce((v,b)=>v*2+b,0);
  return <><Header start={start} /><section className={s.chromeHero}><h1>מחשבה טובה.<br /><span>ביצוע חד.</span></h1><p>המקום שבו הידע שלכם הופך למיומנות בראיון.</p><Action start={start}>להתחיל מהשאלה הראשונה</Action><div className={s.keyStage}><div className={s.keyDeck} dir="ltr"><Image src="/design-worlds/chrome-keys.png" alt="" fill sizes="(max-width:700px) 350px, 660px" priority /><div className={s.keyControls}>{bits.map((b,i)=><button key={i} aria-label={`ביט ${3-i}: ${b}`} aria-pressed={!!b} onClick={()=>setBits(old=>old.map((v,n)=>n===i?1-v:v))}><span>{3-i}</span><b>{b}</b></button>)}<div className={s.enterKey}><ArrowUpLeft size={42} /><small>THINK</small></div></div></div><div className={s.chromeValue}><span>מבינארי לעשרוני</span><code dir="ltr">{bits.join('')} = <output aria-live="polite">{value}</output></code></div></div><span className={s.chromeCaption}>ארבעה ביטים. לחצו על המקשים וגלו מה משתנה.</span></section><div className={s.chromeBand}><strong>פשוט להתחיל.<br />עמוק ככל שתרצו.</strong><p>חומרה, תוכנה וחשיבה לוגית.<br />עם מקום לטעות, לנסות ולהבין.</p></div><TopicFooter start={start} /></>;
}
function Primary({ start }: { start: Start }) {
  const [selected,setSelected]=useState(0);
  return <><Header start={start} /><section className={s.primaryHero}><div className={s.primaryTitle}><h1>ידע.<br /><span>בתנועה.</span></h1><p>הכנה לראיונות שמתחילה בראש שלכם,<br />וממשיכה בידיים.</p><Action start={start} index={selected}>בוחרים שאלה. מתחילים.</Action></div><div className={s.primaryBlocks}><button className={s.yellowBlock} onClick={()=>setSelected(0)} aria-pressed={selected===0}><Cpu size={62} strokeWidth={1} /><strong>חומרה</strong><span>{selected===0?'נבחר לתרגול':'בחרו תחום'} <ArrowUpLeft /></span></button><button className={s.redBlock} onClick={()=>setSelected(1)} aria-pressed={selected===1}><span className={s.codeMark} dir="ltr">{'{ }'}</span><strong>תוכנה</strong><span>{selected===1?'נבחר לתרגול':'בחרו תחום'} <ArrowUpLeft /></span></button><button className={s.blueBlock} onClick={()=>setSelected(2)} aria-pressed={selected===2}><span className={s.primaryCircles}><i /><i /><i /></span><strong>חשיבה לוגית</strong><span>{selected===2?'נבחר לתרגול':'בחרו תחום'} <ArrowUpLeft /></span></button></div></section><div className={s.primaryBottom}><span>הצעד הבא שלכם</span><strong>{samples[selected].title}</strong><button onClick={()=>start(selected)} aria-label="פתיחת השאלה שנבחרה"><ArrowLeft size={30} /></button></div><TopicFooter start={start} /></>;
}
function Arcade({ start }: { start: Start }) {
  const [mission,setMission]=useState(0);
  return <><Header start={start} marker={<Zap size={23} fill="currentColor" />} /><section className={s.arcadeHero}><div className={s.arcadeCopy}><h1>עוד שלב.<br /><em>יותר ביטחון.</em></h1><p>תרגול רציני, אנרגיה אחרת.<br />שאלה קטנה יכולה לפתוח רעיון גדול.</p><Action start={start} index={mission}>נכנסים למשחק</Action><span className={s.arcadeTag}>חומרה · תוכנה · חידות</span></div><div className={s.arcadeMap}><div className={s.mapGrid} /><svg viewBox="0 0 530 430" aria-hidden="true"><path d="M116 255H242V195H392V102" /></svg>{[<Cpu key="cpu" />,<Code2 key="code" />,<Sparkles key="logic" />].map((icon,i)=><button key={i} className={s.mission} data-step={i} data-active={mission===i} onClick={()=>setMission(i)} aria-label={`בחירת שלב ${i+1}: ${samples[i].topic}`} aria-pressed={mission===i}><span>{icon}</span><strong>{i+1}</strong></button>)}<div className={s.missionCard}><h2>{samples[mission].title}</h2><button onClick={()=>start(mission)}>מתחילים <Play size={15} fill="currentColor" /></button></div><div className={s.pixelSpark} aria-hidden="true"><svg viewBox="0 0 64 64"><path d="M24 4H40V24H60V40H40V60H24V40H4V24H24Z" fill="currentColor" /></svg></div></div></section><div className={s.arcadeBanner}><span>שאלה.</span><span>ניסוי.</span><span>קליק בראש.</span></div><TopicFooter start={start} lead="לאן עולים עכשיו?" /></>;
}
function Edition({ start }: { start: Start }) {
  const [row,setRow]=useState(1);
  return <><Header start={start} /><section className={s.editionHero}><div className={s.editionHeadline}><h1>לחשוב<br /><em>מעבר</em><br />לתשובה.</h1><p>יש הבדל בין לדעת את הפתרון<br />לבין להבין איך להגיע אליו.</p></div><div className={s.editionPlate}><div className={s.venn} aria-hidden="true"><i data-on={row>1} /><i data-on={row%2===1} /><span>A</span><span>B</span></div><div className={s.editionTable} dir="ltr">{[0,1,2,3].map(v=><button key={v} aria-pressed={row===v} onClick={()=>setRow(v)}><span>{v>>1} ⊕ {v%2}</span><b>{(v>>1)^(v%2)}</b></button>)}</div><p>שתי אפשרויות. מערכת יחסים אחת.<br />לחצו על שורה ובדקו את פעולת XOR.</p></div><div className={s.editionSide}><span className={s.editorialRule} /><h2>הראיון הבא<br />הוא שיחה.<br />בואו נתכונן.</h2><p>שאלות חומרה ותוכנה,<br />זמן למחשבה<br />ומרחב להסביר את הדרך.</p><Action start={start}>פותחים שאלה</Action></div></section><TopicFooter start={start} lead="מחשבות שכדאי לפתח." /></>;
}
function Solar({ start }: { start: Start }) {
  const [minute,setMinute]=useState(30);
  const hourAngle=180+minute*.5, minuteAngle=minute*6;
  const difference=Math.abs(hourAngle-minuteAngle), angle=Math.min(difference,360-difference);
  return <><Header start={start} /><section className={s.solarHero}><div className={s.solarCopy}><h1>תנו לראש<br /><span>לעבוד.</span></h1><p>הראיון הבא לא צריך להפתיע אתכם.<br />חומרה, תוכנה ושאלות שמשנות זווית.</p><Action start={start} index={2}>תפתיעו אותי בשאלה</Action></div><div className={s.sunDisc}><div className={s.clockFace} aria-label={`שעון 6:${minute===0?'00':minute}, זווית ${angle} מעלות`}><span className={s.twelve}>12</span><span className={s.six}>6</span><i className={s.hourHand} style={{transform:`rotate(${hourAngle}deg)`}} /><i className={s.minuteHand} style={{transform:`rotate(${minuteAngle}deg)`}} /><b /><div className={s.clockNotches}>{Array.from({length:12},(_,i)=><i key={i} style={{transform:`rotate(${i*30}deg)`}} />)}</div></div><div className={s.solarControl}><button onClick={()=>setMinute(v=>(v+15)%60)}><RotateCcw size={17} /> עוד רבע שעה</button><output aria-live="polite">{angle}°</output></div><p>מחוג השעות לא מחכה. חשבתם על זה?</p></div></section><div className={s.solarMarquee} aria-hidden="true"><span>STAY CURIOUS</span><ArrowUpLeft size={76} /><span>KEEP GOING</span></div><TopicFooter start={start} lead="הסקרנות שלכם. המגרש שלנו." /></>;
}
function Tide({ start }: { start: Start }) {
  const [phase,setPhase]=useState(0);
  return <><Header start={start} /><section className={s.tideHero}><h1>כשזה מתחבר,<br /><em>מרגישים את זה.</em></h1><div className={s.tideMiddle}><p>מקום חדש להכנה לראיונות.<br />להפוך סימני שאלה<br />לדרך שאתם יודעים להסביר.</p><Action start={start}>תנו לסקרנות להוביל</Action></div><div className={s.tideWave}><svg viewBox="0 0 1200 220" preserveAspectRatio="none" role="img" aria-label={`הדמיית אות עם היסט ${phase}`}><path className={s.waveFill} d={`M-100 160Q100 ${phase?170:0} 300 110T700 90T1300 120V240H-100Z`} /><path className={s.waveLine} d={`M-100 160Q100 ${phase?170:0} 300 110T700 90T1300 120`} /><path className={s.waveEcho} d={`M-100 180Q100 ${phase?130:35} 300 130T700 110T1300 140`} /></svg><button onClick={()=>setPhase(1-phase)}>שנו את האות <ArrowRight size={19}/></button></div><div className={s.tideJourney}>{['בוחרים כיוון','מנסים בעצמכם','מבינים את הדרך'].map((t,i)=><button key={t} onClick={()=>start(i)}><span>{i+1}</span><strong>{t}</strong><ArrowUpLeft /></button>)}</div></section><TopicFooter start={start} lead="משאלה אחת, לרעיון הבא." /></>;
}
function Noir({ start }: { start: Start }) {
  const [choice,setChoice]=useState<number|null>(null);
  return <><Header start={start} /><section className={s.noirHero}><div className={s.noirType}><h1>לדעת.<br /><span>להסביר.</span><br />להתקדם.</h1><p>הכנה לראיונות טכניים.<br />בהירות היא מיומנות. אפשר לתרגל אותה.</p><Action start={start}>נכנסים לעומק</Action></div><div className={s.noirInterview}><div className={s.noirRail}><span>רגע של מחשבה</span><div><i /><i /><i /></div></div><p>שני קלטים זהים.<br />שער <b dir="ltr">XOR</b> אחד.</p><h2>מה יוצא?</h2><div className={s.noirOptions}>{[0,1].map(n=><button key={n} onClick={()=>setChoice(n)} aria-pressed={choice===n}>{n}<ArrowUpLeft size={20}/></button>)}</div><div className={s.noirFeedback} aria-live="polite">{choice===null?'בחרו תוצאה. תנו להסבר לבוא אחריה.':choice===0?'בדיוק. XOR נותן 1 רק כשהקלטים שונים.':'כמעט. קלטים זהים נותנים 0. נסו את האפשרות השנייה.'}</div><button className={s.noirNext} onClick={()=>start()}>עכשיו, איך הייתם מסבירים את זה? <ArrowLeft size={18}/></button></div></section><div className={s.noirWord} aria-hidden="true" dir="ltr">MAKE IT CLEAR.</div><TopicFooter start={start} /></>;
}

function Workspace({ index, back }: { index: number; back: () => void }) {
  const [hint,setHint]=useState(false), [solution,setSolution]=useState(false), [answer,setAnswer]=useState(''), [sent,setSent]=useState(false);
  const q=samples[index];
  return <main className={s.workspace}><button className={s.back} onClick={back}><ArrowRight size={18}/> חזרה לעיצוב</button><div className={s.workspaceGrid}><section><span>{q.topic}</span><h1>{q.title}</h1><p>{q.prompt}</p><button className={s.secondary} onClick={()=>setHint(!hint)}>{hint?'הסתרת הרמז':'אפשר רמז?'}</button>{hint&&<p className={s.answerNotice}>{q.hint}</p>}</section><section className={s.answerBox}><h2>הדרך שלכם</h2><label htmlFor="concept-answer">הסבירו את הרעיון, ההנחות והבדיקה.</label><textarea id="concept-answer" dir="auto" placeholder="אפשר לכתוב הסבר, פסאודו־קוד או פתרון…" value={answer} onChange={e=>{setAnswer(e.target.value);setSent(false);}} /><button className={s.action} disabled={!answer.trim()} onClick={()=>setSent(true)}>סיום הניסיון <Check size={18}/></button>{sent&&<p role="status" className={s.answerNotice}>הניסיון מוצג בהדמיה בלבד. לא בוצעה הערכה ולא נשמר מידע בחשבון.</p>}<button className={s.secondary} onClick={()=>setSolution(!solution)}>{solution?'הסתרת הפתרון':'הצגת פתרון לדוגמה'}</button>{solution&&<p className={s.answerNotice}>{q.answer}</p>}</section></div></main>;
}
const worlds: Record<ConceptVariant, (props:{start:Start})=>ReactNode> = {ion:Ion,coral:Coral,blueprint:Blueprint,chrome:Chrome,primary:Primary,arcade:Arcade,edition:Edition,solar:Solar,tide:Tide,noir:Noir};
export function ConceptPreview() {
  const params=useSearchParams();
  const direction=conceptDirections.find(d=>d.id===params.get('variant'))??conceptDirections[0];
  const [active,setActive]=useState<number|null>(null);
  const World=worlds[direction.id];
  function start(index=0){setActive(index);window.scrollTo({top:0,behavior:'instant'});}
  return <div className={`${s.root} ${s[direction.id]} ${params.get('motion')==='0'?'':s.moving}`}><div className={s.demo}>הדמיית עיצוב · שאלות לדוגמה · ללא שמירה או הערכה</div>{active===null?<World start={start}/>:<Workspace index={active} back={()=>setActive(null)}/>}<footer className={s.footer}><a href="/design-lab">כל העיצובים <ArrowLeft size={15}/></a><span>JobRun · ללמוד איך לחשוב.</span></footer></div>;
}
